services:
  omeka-mysql-lib-unb-ca:
    image: mariadb:10.3
    command: mysqld --skip-name-resolve
    env_file:
      - ./env/mysql.env
    expose:
      - "3306"
    networks:
      - exhibits.lib.unb.ca
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
  exhibits.lib.unb.ca:
    build:
      context: .
    env_file:
      - ./env/omeka.env
    container_name: exhibits.lib.unb.ca
    expose:
      - "80"
    networks:
      - exhibits.lib.unb.ca
    ports:
      - "3104:80"
    restart: unless-stopped
networks:
  exhibits.lib.unb.ca:
    name: exhibits.lib.unb.ca
volumes:
  mysql-data:
