apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: omeka
    appMajor: "3"
    instance: exhibits.lib.unb.ca
    tier: frontend
    uri: dev-exhibits.lib.unb.ca
    vcsOwner: unb-libraries
    vcsRepository: exhibits.lib.unb.ca
    vcsRef: dev
  name: exhibits-lib-unb-ca
  namespace: dev
spec:
  selector:
    matchLabels:
      uri: dev-exhibits.lib.unb.ca
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: omeka
        appMajor: "3"
        instance: exhibits.lib.unb.ca
        tier: frontend
        uri: dev-exhibits.lib.unb.ca
        vcsOwner: unb-libraries
        vcsRepository: exhibits.lib.unb.ca
        vcsRef: dev
    spec:
      nodeSelector:
        deploy_dev: 'true'
      containers:
        -
          name: exhibits-lib-unb-ca
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 100
            timeoutSeconds: 3
            periodSeconds: 15
          env:
            -
              name: DEPLOY_ENV
              value: dev
            -
              name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: exhibits
                  key: omeka-database
            -
              name: MYSQL_HOSTNAME
              value: omeka-mysql-lib-unb-ca
            -
              name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: exhibits
                  key: omeka-password
            -
              name: MYSQL_PORT
              value: "3306"
            -
              name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: root-password
            -
              name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: exhibits
                  key: omeka-user
            -
              name: NR_INSTALL_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic
                  key: install-key
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          ports:
            -
              containerPort: 80
          volumeMounts:
            -
              mountPath: /app/html/files
              name: omeka-persistent-storage
      priorityClassName: dev-med-priority-services
      imagePullSecrets:
        -
          name: github-container-registry-auth
      restartPolicy: Always
      volumes:
        -
          name: omeka-persistent-storage
          persistentVolumeClaim:
            claimName: exhibits-lib-unb-ca
